#!/bin/bash

function daemonRunning {
	daemon=$1
	
			if [ $(ps -e | egrep \ $daemon$ | wc -l) -gt 0 ]; then
				output "daemon-running $daemon" OK
			else
				output "daemon-running $daemon" FAIL "It's not running"
			fi
}

function processMatch {
	processRegex=$1
			if [ $(ps aux | egrep $processRegex | wc -l) -gt 0 ]; then
				output "process-match $processRegex" OK
			else
				output "process-match $processRegex" FAIL "It's not running"
			fi
}
