#!/bin/bash

appname="sassert"
appversion="0.1"

declare -A opt

while true; do
  case "$1" in
    -v | --version ) cmd="--version"; shift ;;
    -h | --help ) cmd="--help"; shift ;;
    -d | --debug ) opt["debug"]=true; shift ;;
    -q | --quiet | --shutup ) opt["quiet"]=true; shift ;;
    --exists ) cmd=$1; file=$2; shift 2 ;;
    --ownership ) cmd=$1; file=$2; owner=$3; shift 3 ;;
    --permissions ) cmd=$1; file=$2; permissions=$3; shift 3 ;;
    --symlink ) cmd=$1; file=$2; symlinkDestination=$3; shift 3 ;;
    --daemon-running ) cmd=$1; daemon=$2; shift 2 ;;
    --process-match ) cmd=$1; processRegex=$2; shift 2 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done 

# let's default to the syntax view
if [ ! $cmd ]; then
	cmd="--help"
fi

source ./filesystem
source ./procs
#source ./network


if [ $cmd ]; then
	case $cmd in
		"--version" )
			if [ ! ${opt["quiet"]} ]; then
				echo "thought you'd never ask."
				echo "$appname $appversion"
			else
				echo $appversion;
			fi ;;
		"--help" )
			if [ ! ${opt["quiet"]} ]; then
				echo "$appname $appversion"
				echo ""
				echo "Usage:"
				echo "	--exists [dir/file]			Verify if dir or file exists"
				echo "	--permissions [dir/file] [perms]	Verify permissions (in numeric format)"
				echo "	--ownership [dir/file] [username]	Verify ownership"
				echo "	--symlink [file] [destination]		Verify the destination of the symlink"
				echo "	-v, --version				Show version"
				echo ""
				echo "Flags:"
				echo "	-q, --quiet				Quiet"
				echo ""
			else
				echo "no help for you, buddy.";
			fi ;;
		"--exists" )
			exists $file ;;
		"--ownership" )
			ownership $file $owner ;;
		"--permissions" )
			permissions $file $permissions ;;
		"--symlink" )
			symlink $file $symlinkDestination ;;
		"--daemon-running" )
			daemonRunning $daemon ;;
		"--process-match" )
			processMatch $processRegex ;;
    		-- ) shift; break ;;
		* ) break ;; 
	esac
else
	echo "That's not how it works, dude."
fi
